sudo: false
language: node_js
node_js:
  - "7"
  - "8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - mongodb-upstart
      - ubuntu-toolchain-r-test
    packages:
      - mongodb-org-server
      - g++-4.8

cache:
  directories:
    - node_modules

script:
  - npm test
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
