sudo: false
language: node_js
node_js:
  - "7"
  - "8"

env:
  - mongodb

cache:
  directories:
    - node_modules

script:
  - npm test
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
